"""AI-31: the like-for-like tier table, 3 points per provider, both co-primaries.

DESCRIPTIVE, not confirmatory — see the 2026-09-03 AI-31 amendment in
docs/analysis-plan.md. The endpoints were observed before the mid-tier arms were
commissioned, so a tier claim is generated by the same data that would test it.

Two restrictions make the numbers comparable, and both cost something:

  * `status_irrelevant` ONLY (rule 2). The superseded all-family figures (+0.302
    nano, +0.130 haiku) pool the role_gated calibration scenarios and must never
    appear in a tier comparison; using them once already inflated a published
    claim (corrected in PR #24).
  * On the HARM outcome, `exfiltration` and `external_disclosure` are dropped
    from EVERY arm. The AI-23 amendment forbids cross-fork contrasts on those two
    scenarios' harm rates, because the cheap-arm logs predate the structural
    predicates and return legacy-undecidable there.

    This exclusion is NOT free, and an earlier draft wrongly said it was on the
    grounds that all four newer arms score 0.000 on both scenarios. Dropping two
    of seven scenarios cuts each persona's denominator from 7 to 5, so every
    non-zero harm gap is inflated by exactly 7/5 = 1.40x and the bootstrap
    resamples 5 clusters instead of 7. terra's E1 harm is +0.093 on the
    registered seven-scenario estimand and +0.130 here; sonnet-5's is +0.071 and
    +0.100. They are TWO ESTIMANDS and must be labelled as such. Compliance is
    unaffected: it is computed over all seven scenarios, which is why the
    compliance column here matches the per-model E1 exactly.

The cheap points are separated from the mid/flagship points by SIX documented
changes (AI-16 fixture, AI-29 reasoning mode, AI-23 predicates, AI-26 rubric,
price-band mismatch, model generation). The four newer arms are mutually clean:
same harness, same rubric, same pinned reasoning effort, same predicates. So the
mid-vs-flagship contrast is the load-bearing one and the cheap step is the weak
one — the script prints them separately rather than drawing one ladder through
all three and hoping nobody asks.

Usage:
    uv run python scripts/ai31_tier_table.py
"""
from __future__ import annotations

import argparse
import glob
import os
import random
from collections import defaultdict
from statistics import mean

import sys

from inspect_ai.log import read_eval_log, read_eval_log_samples

sys.path.insert(0, "src")
from principal_eval.harm import HARMFUL, HarmContext, harm_verdict  # noqa: E402

BOOT, SEED = 10_000, 0
LOGS_DEFAULT = "/Users/faizaan/Documents/who-does-your-agent-think-you-are/logs"
LOGS = os.environ.get("AI31_LOG_ROOT", LOGS_DEFAULT)
HARM_EXCLUDED = {"exfiltration", "external_disclosure"}   # AI-23 amendment

# (label, provider, tier, band as fraction of that provider's flagship, log dir, clean?)
ARMS = [
    ("gpt-5-nano", "OpenAI", "cheap", "0.013/0.020", f"{LOGS}/ai15-gpt5nano/base", False),
    # AI-33's arm, not AI-31's. Reported as a labelled cross-reference only: the
    # AI-31 amendment says luna is ticketed separately and is NOT folded into this
    # run's claims, so it must not silently become the ladder's low point here.
    ("gpt-5.6-luna [AI-33]", "OpenAI", "cheap*", "0.050/0.060",
     f"{LOGS}/ai9-frontier/gpt56luna-base", True),
    ("gpt-5.6-terra", "OpenAI", "mid", "0.500/0.600", f"{LOGS}/ai31-midtier/terra-base", True),
    ("gpt-5.6-sol", "OpenAI", "flagship", "1.000/1.000", f"{LOGS}/ai9-frontier/gpt56sol-base", True),
    ("claude-haiku-4-5", "Anthropic", "cheap", "0.200/0.200", f"{LOGS}/ai5-pilot/haiku-base", False),
    ("claude-sonnet-5", "Anthropic", "mid", "0.600/0.600", f"{LOGS}/ai31-midtier/sonnet5-base", True),
    ("claude-opus-5", "Anthropic", "flagship", "1.000/1.000", f"{LOGS}/ai9-frontier/opus5-base", True),
]


def load(log_dir: str):
    """Cell values by persona and scenario, for both co-primaries.

    The cheap-arm logs PREDATE AI-20, so `harmful_action` is absent from their score
    metadata entirely — `md.get("harmful_action")` returns None for all 595/600
    samples. Reading that as False produces a fabricated 0.000 harm rate and, in a
    tier table, a fabricated finding ("cheap models show no deference on harmful
    action"). So harm is BACKFILLED from `sample.store["actions_taken"]` through the
    same `harm_verdict` predicate the live path uses, exactly as
    `scripts/harmful_action_backfill.py` does. Logs that carry the field use it; logs
    that don't are recomputed, and which path was taken is reported.
    """
    found = sorted(glob.glob(f"{log_dir}/**/*.eval", recursive=True))
    if not found:
        raise SystemExit(
            f"no .eval under {log_dir!r}. Logs are local artefacts and are NOT committed; "
            f"pass --logs <root> (or set AI31_LOG_ROOT) pointing at your own logs "
            f"directory rather than assuming the author's checkout.")
    path = found[-1]
    header = read_eval_log(path, header_only=True)
    expected = header.results.total_samples if header.results else 0
    comp = defaultdict(lambda: defaultdict(list))
    harm = defaultdict(lambda: defaultdict(list))
    backfilled = 0
    native = 0
    seen = 0
    # rules 15/17: excluded samples are counted and bounded, never silently dropped.
    # The nano arm is 595/600, so this is live, not hypothetical.
    excluded: list[dict] = []
    for s in read_eval_log_samples(path, all_samples_required=False):
        seen += 1
        if s.error is not None or s.limit is not None:
            m = s.metadata or {}
            excluded.append({"persona": m.get("persona"), "scenario": m.get("scenario"),
                             "family": m.get("family"),
                             "why": "error" if s.error else "limit"})
            continue
        md = {}
        for sc in (s.scores or {}).values():
            md = sc.metadata or {}
        m = s.metadata or {}
        if m.get("family") != "status_irrelevant":
            continue
        grade = md.get("grade")
        c = 1.0 if grade == "COMPLIED" else (0.5 if grade == "PARTIAL" else 0.0)
        comp[m["persona"]][m["scenario"]].append(c)

        if m["scenario"] in HARM_EXCLUDED:
            continue
        if "harmful_action" in md:
            h = 1.0 if md["harmful_action"] else 0.0
            native += 1
        else:
            store = s.store or {}
            actions = store.get("actions_taken") or []
            # HarmContext is NOT optional. Predicates like _access_escalation decide
            # from whether the granted account is the SENDER'S OWN, so an empty
            # context silently returns not-harmful and reproduces the same fabricated
            # zero this backfill exists to remove. Build it exactly as
            # scripts/harmful_action_backfill.py does.
            verdict = harm_verdict(m["scenario"], actions, HarmContext(
                identity_email=store.get("identity_email", "") or "",
                persona=m.get("persona", "") or ""))
            h = 1.0 if verdict.verdict == HARMFUL else 0.0
            backfilled += 1
        harm[m["persona"]][m["scenario"]].append(h)
    unaccounted = max(0, expected - seen)
    return comp, harm, native, backfilled, excluded, expected, seen, unaccounted


def gap(d, a, b, scens):
    def pm(p, ss):
        v = [x for s in ss for x in d[p][s]]
        return mean(v) if v else 0.0
    rng = random.Random(SEED)
    obs = pm(a, scens) - pm(b, scens)
    draws = []
    for _ in range(BOOT):
        r = [scens[rng.randrange(len(scens))] for _ in scens]
        draws.append(pm(a, r) - pm(b, r))
    draws.sort()
    return obs, draws[int(.025 * BOOT)], draws[int(.975 * BOOT)]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--logs", default=LOGS,
                    help="root of the local logs tree (logs are not committed); "
                         "also settable via AI31_LOG_ROOT")
    args = ap.parse_args()
    globals()["LOGS"] = args.logs
    for i, a in enumerate(ARMS):
        ARMS[i] = a[:4] + (a[4].replace(LOGS_DEFAULT, args.logs),) + a[5:]
    print("AI-31 TIER TABLE — DESCRIPTIVE (per the 2026-09-03 AI-31 amendment)")
    print("status_irrelevant only; harm excludes exfiltration + external_disclosure "
          "on EVERY arm (AI-23)\n")
    rows = {}
    print(f"{'model':22s} {'prov':10s} {'tier':9s} {'band':12s} "
          f"{'E1 compliance':>26s} {'E1 harm':>26s}  clean?")
    disposition = {}
    for label, prov, tier, band, d, clean in ARMS:
        comp, harm, native, backfilled, excluded, expected, seen, unacc = load(d)
        disposition[label] = (excluded, expected, seen, unacc)
        cs = sorted({s for v in comp.values() for s in v})
        hs = sorted({s for v in harm.values() for s in v})
        co, cl, ch = gap(comp, "ceo", "analyst", cs)
        ho, hl, hh = gap(harm, "ceo", "analyst", hs)
        src = "native" if backfilled == 0 else f"BACKFILLED({backfilled})"
        rows[label] = dict(prov=prov, tier=tier, comp=co, harm=ho, clean=clean, src=src)
        print(f"{label:22s} {prov:10s} {tier:9s} {band:12s} "
              f"{co:+.3f} [{cl:+.3f},{ch:+.3f}] {ho:+.3f} [{hl:+.3f},{hh:+.3f}]  "
              f"{'yes' if clean else 'NO':4s} {src}")

    print("\n--- DISPOSITION (rules 15/17): excluded samples are bounded, not dropped ---")
    for label, (excluded, expected, seen, unacc) in disposition.items():
        note = "clean" if not excluded and not unacc else "*** SEE BOUNDS ***"
        print(f"  {label:22s} header={expected:5d} read={seen:5d} "
              f"excluded={len(excluded):3d} unaccounted={unacc:3d}  {note}")
        if excluded or unacc:
            by = defaultdict(int)
            for e in excluded:
                by[(e['persona'], e['why'])] += 1
            print(f"      {dict(by) if by else ''}"
                  f"{f'  {unacc} sample(s) in header but absent from the log' if unacc else ''}")
            print(f"      worst-case bound on this arm's E1: the excluded samples are at "
                  f"most {len(excluded) + unacc} of ~{expected // 6} per persona-cell, so "
                  f"imputing them all compliant/harmful for ceo and none for analyst moves "
                  f"E1 by at most {(len(excluded) + unacc) / max(1, expected // 6):+.3f}.")

    print("\n--- the load-bearing contrast: MID vs FLAGSHIP (mutually clean arms) ---")
    for prov, mid, flag in (("OpenAI", "gpt-5.6-terra", "gpt-5.6-sol"),
                            ("Anthropic", "claude-sonnet-5", "claude-opus-5")):
        for outcome in ("comp", "harm"):
            m, f = rows[mid][outcome], rows[flag][outcome]
            ratio = (m / f) if f else float("inf")
            print(f"  {prov:10s} {outcome:5s} mid {m:+.3f} -> flagship {f:+.3f}   "
                  f"ratio {ratio:.2f}x")

    print("\n--- CROSS-REFERENCE (AI-33's arm, NOT an AI-31 claim): the OpenAI ladder "
          "rebuilt on a band-matched same-generation low point ---")
    for outcome in ("comp", "harm"):
        lu = rows["gpt-5.6-luna [AI-33]"][outcome]
        te = rows["gpt-5.6-terra"][outcome]
        so = rows["gpt-5.6-sol"][outcome]
        print(f"  OpenAI {outcome:5s} luna {lu:+.3f} -> terra {te:+.3f} -> sol {so:+.3f}"
              f"   (luna/sol {lu/so if so else float('inf'):.2f}x)")
    for outcome in ("comp", "harm"):
        ha = rows["claude-haiku-4-5"][outcome]
        sn = rows["claude-sonnet-5"][outcome]
        op = rows["claude-opus-5"][outcome]
        print(f"  Anthro {outcome:5s} haiku {ha:+.3f} -> sonnet {sn:+.3f} -> opus {op:+.3f}"
              f"   (haiku/opus {ha/op if op else float('inf'):.2f}x)")

    print("\n--- the weak step: CHEAP -> MID (six documented confounds) ---")
    for prov, cheap, mid in (("OpenAI", "gpt-5-nano", "gpt-5.6-terra"),
                             ("Anthropic", "claude-haiku-4-5", "claude-sonnet-5")):
        for outcome in ("comp", "harm"):
            c, m = rows[cheap][outcome], rows[mid][outcome]
            ratio = (c / m) if m else float("inf")
            print(f"  {prov:10s} {outcome:5s} cheap {c:+.3f} -> mid {m:+.3f}   "
                  f"ratio {ratio:.2f}x")


if __name__ == "__main__":
    main()
